### ISSUE TITLE
Add ability to group and reorder pages

### ISSUE THREAD

**Issue by Keith94** [WaldiPL/webpageScanner#1]
Hi and thanks for the useful add-on.

It would be nice having the ability to organize the scan list via dragging items to change their order, as well as creating folders to add items in similar to Firefox's places UI. Thoughts?

**Comment by WaldiPL** [comment]
The current version has a few bugs, tomorrow I will add a corrected version.

**Comment by WaldiPL** [comment]
If you can please test the latest version [1.3.0](https://github.com/WaldiPL/webpageScanner/blob/master/xpi/Web%20Pages%20Scanner%201.3.0.xpi)
I worked on it a few days and may be some bugs.

**Comment by Keith94** [comment]
Looks really good so far from what I tested. Great work!

I was moving items around but at some point the popup stopped working. In the browser console shows: `TypeError: lastFolder is undefined[Learn More]  sidebar.js:169:6`

A minor thing: the folder should probably change color (blue?) when you're dropping an item into it.

**Comment by WaldiPL** [comment]
I can't locate the source of this bug.
Go to `about:debugging` , then find the Web pages scanner extension and click `Debug`. Open the console and paste the code below

> browser.storage.local.get('sort').then(e=>{let a='';e.sort.forEach((v,i)=>{a+=\`>|${i}| ${v} \`;});console.log(a);});

Press enter and then copy the returned string, and send it to me.

Finally paste into the console
`browser.storage.local.remove('sort');`
and restart your browser to fix the scan list.

**Comment by Keith94** [comment]
Here's the returned string:

>|0| item5,folder1503297667290,item,,false >|1| item11,folder1503297667290,item,,false >|2| item17,folder1503297667290,item,,false >|3| item87,folder1503297667290,item,,false >|4| item18,folder1503297667290,item,,false >|5| item21,folder1503297667290,item,,false >|6| item22,folder1503297667290,item,,false >|7| item23,folder1503297667290,item,,false >|8| item24,folder1503297667290,item,,false >|9| item25,folder1503297667290,item,,false >|10| item26,folder1503297667290,item,,false >|11| item16,folder1503297667290,item,,false >|12| item15,folder1503297667290,item,,false >|13| item0,folder1503297667290,item,,false >|14| item86,folder1503297667290,item,,false >|15| item19,folder1503297667290,item,,false >|16| item20,folder1503297667290,item,,false >|17| item27,folder1503297667290,item,,false >|18| item28,folder1503297667290,item,,false >|19| item29,folder1503297667290,item,,false >|20| item30,folder1503297667290,item,,false >|21| item31,folder1503297667290,item,,false >|22| item32,folder1503297667290,item,,false >|23| item33,folder1503297667290,item,,false >|24| item34,folder1503297667290,item,,false >|25| item35,folder1503297667290,item,,false >|26| item36,folder1503297667290,item,,false >|27| item37,folder1503297667290,item,,false >|28| item38,folder1503297667290,item,,false >|29| item39,folder1503297667290,item,,false >|30| item40,folder1503297667290,item,,false >|31| item41,folder1503297667290,item,,false >|32| item42,folder1503297667290,item,,false >|33| item43,folder1503297667290,item,,false >|34| item44,folder1503297667290,item,,false >|35| item45,folder1503297667290,item,,false >|36| item46,folder1503297667290,item,,false >|37| item47,folder1503297667290,item,,false >|38| item48,folder1503297667290,item,,false >|39| item49,folder1503297667290,item,,false >|40| item50,folder1503297667290,item,,false >|41| item51,folder1503297667290,item,,false >|42| item52,folder1503297667290,item,,false >|43| item53,folder1503297667290,item,,false >|44| item54,folder1503297667290,item,,false >|45| item55,folder1503297667290,item,,false >|46| item56,folder1503297667290,item,,false >|47| item57,folder1503297667290,item,,false >|48| item58,folder1503297667290,item,,false >|49| item59,folder1503297667290,item,,false >|50| item60,folder1503297667290,item,,false >|51| item61,folder1503297667290,item,,false >|52| item62,folder1503297667290,item,,false >|53| item63,folder1503297667290,item,,false >|54| item64,folder1503297667290,item,,false >|55| item65,folder1503297667290,item,,false >|56| item66,folder1503297667290,item,,false >|57| item67,folder1503297667290,item,,false >|58| item68,folder1503297667290,item,,false >|59| item69,folder1503297667290,item,,false >|60| item70,folder1503297667290,item,,false >|61| item71,folder1503297667290,item,,false >|62| item74,folder1503297667290,item,,false >|63| item83,folder1503297667290,item,,false >|64| item84,folder1503297667290,item,,false >|65| folder1503299237355,root,folder,Software,true >|66| item3,folder1503299237355,item,,false >|67| item8,folder1503299237355,item,,false >|68| item9,folder1503299237355,item,,false >|69| item10,folder1503299237355,item,,false >|70| item6,folder1503299237355,item,,false >|71| item4,folder1503299237355,item,,false >|72| item13,folder1503299237355,item,,false >|73| item7,folder1503299237355,item,,false >|74| item12,folder1503299237355,item,,false >|75| item14,folder1503299237355,item,,false >|76| item1,folder1503299237355,item,,false >|77| item72,folder1503299237355,item,,false >|78| folder1503299318058,root,folder,Other,true >|79| item2,folder1503299318058,item,,false >|80| item73,folder1503299318058,item,,false >|81| item75,folder1503299318058,item,,false >|82| item76,root,item,,false >|83| item77,root,item,,false >|84| item78,root,item,,false >|85| item79,root,item,,false >|86| item80,root,item,,false >|87| item81,root,item,,false >|88| item82,root,item,,false >|89| item83,root,item,,false >|90| item85,root,item,,false

**Comment by WaldiPL** [comment]
In version [1.3.1](https://github.com/WaldiPL/webpageScanner/blob/master/xpi/Web%20Pages%20Scanner%201.3.1.xpi?raw=true) bug has been removed.

**Comment by Keith94** [comment]
Great, both seem to be fixed. :)

Is it possible to add a button that sorts pages by name alphabetically? But sort them within their respective folders.

**Comment by WaldiPL** [comment]
Currently, no such function is planned.
