### ISSUE TITLE
Scanned items were deleted

### ISSUE THREAD

**Issue by Keith94** [WaldiPL/webpageScanner#10]
I updated to the most recent version (1.3.3?) and all the scan list items I had were gone. Any way to retrieve them?

**Comment by WaldiPL** [comment]
I can not reproduce this bug.

Go to about:debugging , then find the Web pages scanner extension and click Debug. Open the console and paste the code below
> browser.storage.local.get('sites').then(e=>{console.log(e.sites.length);});

If the returned value is 0 then the data can not be recovered.
In the next version will add the ability to create a backup of the database.

**Comment by Keith94** [comment]
I get a value of 3 apparently
>Promise { <state>: "pending" }
3

What can I do?

**Comment by WaldiPL** [comment]
In version 1.3.4 i have added the ability to create a backup.
Also, the database is created only once after the installation of the extension. Earlier every time the browser started, the script checked whether the database existed.
Xpi file I will add tomorrow.
