### ISSUE TITLE
Publish new releases on Firefox's Add-on website

### ISSUE THREAD

**Issue by sphh** [WaldiPL/webpageScanner#11]
I noticed that the version on [Firefox's Add-on website](https://addons.mozilla.org/en-US/firefox/addon/web-pages-scanner/?src=search) is **1.2.5**, on [github's release site](https://github.com/WaldiPL/webpageScanner/releases) **1.2.6** and hidden in the [source tree's xpi directory](https://github.com/WaldiPL/webpageScanner/releases) **1.3.5**.

Do you plan to push the latest version to the Add-on website, so that it can be updated automatically? Thanks.

**Comment by WaldiPL** [comment]
Thanks for the reminder, I forgot to upload the latest version.
Version 1.3.6 should soon be available.

**Comment by sphh** [comment]
Terrific! Thanks.
