### ISSUE TITLE
Only a White Page

### ISSUE THREAD

**Issue by nille02** [WaldiPL/webpageScanner#15]
On some Websites i get only a white site if changes are found.

**Comment by WaldiPL** [comment]
Sometimes changes involve parts of code that are not visible directly to the user, eg js script, css style, element attributes.

**Comment by nille02** [comment]
Its not even happen after a change. i remove and install the addon again and add only one site. klick on this single site gibes me the blank page.

**Comment by WaldiPL** [comment]
I will try to find the cause of this problem.
Temporarily, you can use an old script where the problem does not occur.
Check the box in the options:
`Use old comparing script (faster but less accurate)`

**Comment by nille02** [comment]
With the old method its working.

**Comment by WaldiPL** [comment]
I found the cause of the problem. The bug will be removed in the next version.
