### ISSUE TITLE
Next/previous change button

### ISSUE THREAD

**Issue by sphh** [WaldiPL/webpageScanner#16]
I love your Web Pages Scanner!

Do you think it's possible to add a "Next change" and a "Previous change" button when the changes are shown? This would allow one to quickly jumping to the next/previous change without visually scanning for the yellow marks.

**Comment by WaldiPL** [comment]
I will add this function in the next version.
Some links may be marked twice, and sometimes changes may be invisible, but otherwise everything is ok.
