### ISSUE TITLE
Updated webpages not highlighting in sidebar

### ISSUE THREAD

**Issue by tomrich84** [WaldiPL/webpageScanner#17]
Since Tuesday 5th December, my web pages scanner has been scanning ok, and has highlighted the number of webpages updated. HOWEVER, in the sidebar, it is NOT highlighting the pages that have updates. I would rather not have to open 100+ pages every morning in one go on my web browser! Is there a settings/bug here?

**Comment by WaldiPL** [comment]
The extension was not updated. Do you changed any settings?
Does change detection work correctly? And the problem is only lack of highlight?

**Comment by tomrich84** [comment]
I have played with the settings AFTER the issue arose, but not before. Correct, the issue is the lack of higlighting the changed pages.

**Comment by WaldiPL** [comment]
Do you use a dark theme? In a dark theme, there is a similar problem, only the left border is blue.

You can use the `Open changed pages` button to open all pages on which changes have been detected.

**Comment by tomrich84** [comment]
I do, but so does my colleague; but they do not have the same issue.

**Comment by WaldiPL** [comment]
Is the problem still exists in version 1.5.0?

**Comment by tomrich84** [comment]
The situation seems to have resolved itself, when i reset the theme to dark. Odd, but there we go!

**Comment by tomrich84** [comment]
This issue has re-appeared again, as of this morning (2nd Jan)
