### ISSUE TITLE
request

### ISSUE THREAD

**Issue by jardob** [WaldiPL/webpageScanner#19]
Hallo,
The webpageScanner works well, but the highest frequency of scanning is "1 hour". Could you add the possibility to scan pages in minutes (f.e. 5/10/15 min. interval), please?
Best regards,
Jaroslav

**Comment by WaldiPL** [comment]
Currently, the scanner is run every hour, so changing the frequency in the page settings below 60 minutes would not have the desired effect. Frequent startup of the scanner (eg every 5 minutes) can cause performance problems. In the future I will try to add the possibility of changing the frequency of the scanner's launch.

**Comment by WaldiPL** [comment]
Fixed in version 1.7.0
For proper operation, change the "Frequency of automatic scanner startup" in the options
