### ISSUE TITLE
Scan rate and mode cannot be changed

### ISSUE THREAD

**Issue by Keith94** [WaldiPL/webpageScanner#2]
For some reason, clicking on the scan every/mode options does nothing. One time it did pop up a menu list, but that seems to have stopped working. I'm using Nightly on Windows.

**Comment by WaldiPL** [comment]
This is related to the [bug 1190679](https://bugzilla.mozilla.org/show_bug.cgi?id=1190679), now I can`t find the right thread to follow him. You can also change the "extensions.webextensions.remote" in about:config, so that this options will work fine again.

**Comment by Keith94** [comment]
Looks like it started working again since a few days ago.
