### ISSUE TITLE
Import / Export

### ISSUE THREAD

**Issue by ubahwu** [WaldiPL/webpageScanner#20]
Dear Sir,

I'm trying to import pages from existing firefox bookmark folder but seems failed.
Wish to have proper indication from your kindly help.

Best Regards,

ubahwu

**Comment by WaldiPL** [comment]
Has any message been displayed?
Do other functions work correctly.

**Comment by ubahwu** [comment]
Dear WaldiPL,

Thanks for your reply.

It works! 
I apologized for not upgrading to FF 57 first.
Thanks for this excellent extension.

ubahwu
