### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by toxomo** [WaldiPL/webpageScanner#21]
![image](https://user-images.githubusercontent.com/36037716/35677940-775a914c-078c-11e8-80ef-bfeb612f75c9.png)
![image](https://user-images.githubusercontent.com/36037716/35677989-a479bec8-078c-11e8-88f6-ba03e78b0d97.png)

I use nightly 60.0a1
You see, if the title is very short, the panel is messed up.
And if i want to edit or delete the item, the panel is not expanded automatically. I can only see one line.

**Comment by WaldiPL** [comment]
Are you using custom styles, eg. UserChrome.css ?

**Comment by toxomo** [comment]
No. I only use stylus.

**Comment by WaldiPL** [comment]
The problem will be fixed in the next version.
