### ISSUE TITLE
Next/previous change button should center the changes

### ISSUE THREAD

**Issue by sphh** [WaldiPL/webpageScanner#22]
Thank you for implementing the next/previous change buttons (#16).

When I press the next button, the change is shown at the bottom of the page. IMHO it would be great if it he changed part would be centred vertically on the page (in the middle of the page), so that it is easy to see the "surrounding" of the change. This would help to see the changes made in the context of the page.

**Comment by WaldiPL** [comment]
For Firefox 57+ changes are centered on the screen.

**Comment by sphh** [comment]
Ok. I am on Waterfox 56.0.4.1 (based on Firefox 56). Any changes to center them on these legacy browsers?

**Comment by WaldiPL** [comment]
I do not plan support for older versions. BTW this feature is available only in Firefox 58+
