### ISSUE TITLE
Some pages are shown as empty

### ISSUE THREAD

**Issue by sphh** [WaldiPL/webpageScanner#23]
Some pages are shown empty, e.g. if I want to track the changes on radio-browser.info, I would look for changes at https://www.radio-browser.info/gui/#/lastchange.

I guess this is because the webpage is created dynamically via JavaScript.

Is there a way to track changes on these pages?

**Comment by WaldiPL** [comment]
Unfortunately, it is not possible to scan pages that are generated by JS.

**Comment by sphh** [comment]
That's really unfortunate!

If there is absolutely no way to get this working, you might want to close this issue.
