### ISSUE TITLE
How to add a new folder to web pages scanner

### ISSUE THREAD

**Issue by tomrich84** [WaldiPL/webpageScanner#26]
I already have a number of folders in my web pages scanner, but wish to add a new folder which contains bookmarks from another person. This person did not use web pages scanner and so the bookmarks are saved out as .bak and .orig files. Any advice greatly appreciated!

**Comment by WaldiPL** [comment]
WPS can import pages only from a Firefox bookmark folder or a file created by WPS. You can use the program, which these files were generated and try to save the pages as a bookmarks. You can also manually add pages to WPS.
