### ISSUE TITLE
Idea: monitor only part of a page for changes

### ISSUE THREAD

**Issue by knochenhans** [WaldiPL/webpageScanner#29]
It would be great to be able to select a part of page that should be scanned and monitored for changes, instead of the whole page. This function would make this addon a lot more effective.

**Comment by WaldiPL** [comment]
In version 1.8.5, I added this function.
Please test it and send feedback.

**Comment by knochenhans** [comment]
Wow, thanks! The selector seems off when I edit an existing page via the top bar edit button in the page view (works as expected when I open the selector via the sidebar, though). Scanning seems fine so far, I’ll test it a bit. Thanks again for including this function, this is a big help for me!
