### ISSUE TITLE
Add badge to toolbar button

### ISSUE THREAD

**Issue by Keith94** [WaldiPL/webpageScanner#3]
Can you show a badge when updated items are found? Because I would rather disable the notifications.

![image](https://user-images.githubusercontent.com/5490615/29180588-16529624-7dad-11e7-8cb6-440c3ee6b875.png)

**Comment by WaldiPL** [comment]
Thanks for reporting a problem.
I added the badge in version 1.2.4.

**Comment by Keith94** [comment]
And thanks for adding it! :)
