### ISSUE TITLE
[Feature Request] Optionally(?) show the scan list on the options page too

### ISSUE THREAD

**Issue by FatOrangutan** [WaldiPL/webpageScanner#30]
Trying to migrate my 100+ items from Distill but:

1) Using the popup to do this is difficult because the popup (as expected) isn't modal. It disappears every time I click outside.
2) The sidebar is much better and is what I'm using right now but it has a limited width (even if I adjust its width to the maximum that it can be) so I can't see much of the titles of the scan pages, especially if I'm inside a folder or two.

So I think it would be an improvement to show the list as a dedicated 'tab', alongside the current ones of Options, Management, Changelog, Support.

BTW, and also sorry for asking a question here but I don't know where else to ask: Does the `Frequency of automatic scanner startup [min]` override the `Scan every:` option of individual scan items? Like if I have the former set to 60mins (default) and one of the items on my scan list is set to `Scan every: 10 minutes` then will it be scanned every 60mins or 10? Thanks.

**Comment by WaldiPL** [comment]
In the next version, I will add a link to the "Scan List" on the options page. Currently, you can open the options and change the address of the page. eg.
`moz-extension://[random_string]/options.html#options` > `moz-extension://[random_string]/sidebar.html`

You must change `Frequency of automatic scanner startup [min]` to 10
