### ISSUE TITLE
"Open changed pages" needs a lot of memory

### ISSUE THREAD

**Issue by sphh** [WaldiPL/webpageScanner#33]
If Web Pages Scanner detects a lot of changed pages and I open all those pages with the `Open changed pages` menu from the toolbar button, Firefox needs a lot of memory. In my system monitor I can literally watch all memory filling up. Then my Linux system stops to respond (mouse cannot be moved, system monitor freezes, no input via keyboard). I guess, Linux tries to swap the memory to the swap partition. Sometimes the system becomes responsible again, sometimes it does not and I have to reset the computer.

Firefox: 64.0 (64-bit)
Web Pages Scanner: 1.9.1
Memory: 8 GB

Is there anything to help debugging this problem?

Possible solution: Only open one page and add the possibility to jump to the previous/next changed page (e.g. via buttons in the header and/or menu items in the toolbar button)...

**Comment by WaldiPL** [comment]
Try to change `Delay in opening next pages in new tabs [s]` to e.g. 15.

**Comment by sphh** [comment]
I increased the `Delay in opening next pages in new tabs [s]`. If I am quick enough and close the changed page immediately before Web Pages Scanner opens a lot of other changed pages, I don't run out of memory. This works as a workaround for now.
