### ISSUE TITLE
Gitter not working

### ISSUE THREAD

**Issue by sphh** [WaldiPL/webpageScanner#34]
Is there a possibility to get Gitter (e.g. https://gitter.im/linux-surface) working?

At the moment (Web Pages Scanner 1.9.1 and Firefox 64.0), I get the following:
![image](https://user-images.githubusercontent.com/4856462/51107309-b6eab080-17ee-11e9-9ad5-fc21179f3a44.png)

**Comment by WaldiPL** [comment]
You can open the page from the frame and add it to the scan list.
![](https://i.imgur.com/Irbm64o.png)

**Comment by sphh** [comment]
Thank you for your help. I added the frames and hope that it will work. I'll close this for now.

BTW I thought frames are so yesterday that I never considered it, that gitter uses it...

**Comment by sphh** [comment]
I can confirm that the approach outlined by @WaldiPL works. Thanks!
