### ISSUE TITLE
Scan a part of the page not working

### ISSUE THREAD

**Issue by Cupbox** [WaldiPL/webpageScanner#35]
Hello.
The mentioned feature does not work for me.
As an example I monitored "#post_content15814" in [Everything Beta builds page](https://www.voidtools.com/forum/viewtopic.php?f=2&t=5718) but your tool persists in scanning the whole page for changes.

**Comment by WaldiPL** [comment]
Changes are detected only in the selected element. The page preview shows all changes, including those that are outside the selected element.

In the above example, the correct CSS selector is `#post_content15814 > DIV:nth-child(3) `

`#post_content15814` also contains a links (eg user's profile). Addresses of these links may change dynamically (session ID), this causes detection of changes on the page.

**Comment by Cupbox** [comment]
Thank you for making that clear. I was not aware that the page preview showed changes outside selection scope.

**Comment by WaldiPL** [comment]
In the next version you will be able to hide changes that are outside the selected element.
