### ISSUE TITLE
Unable to add pages to scanner

### ISSUE THREAD

**Issue by tomrich84** [WaldiPL/webpageScanner#36]
I am now unable to add pages to my bookmarks list for web pages scanner. I have tried both way of adding; direct from the webpage right click; and also via the extension, but none are working. Is this a bug? I have been able to add pages in 2019, but something now seems to have gone wrong. 

Thanks

**Comment by WaldiPL** [comment]
Please open the "Browser Console" (Ctrl+Shift+J)
Are there any errors after trying to add a page?

**Comment by tomrich84** [comment]
Yes there is - Error: [Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://extensions/content/child/ext-storage.js :: fireOnChanged :: line 139"  data: no]

![Capture1](https://user-images.githubusercontent.com/34336677/55547992-689ccd80-56ca-11e9-952c-4c67c0efd142.PNG)

**Comment by WaldiPL** [comment]
Try disabling other extensions and add the page again.

**Comment by tomrich84** [comment]
That did not work unfortunately

**Comment by WaldiPL** [comment]
Do other extension functions work correctly?

1. Open the extension settings
2. Open the console (Ctrl+Shift+K)
3. Paste `await browser.storage.local.get("sites")` and press enter

Does the result look similar?
![](https://i.imgur.com/p9z3uCJ.png)

**Comment by tomrich84** [comment]
Yes, the functions appear to be working correctly. 
No, the result doest not look similar. However, I have now found that the scan list can be accessed via the extensions (or add-ons) settings; by clicking on this scanlist icon, is shows an exact duplicate of the list - and also showing the missing pages added! 

![image](https://user-images.githubusercontent.com/34336677/55612395-1918d900-5780-11e9-86b3-dcea366b5d76.png)

**Comment by WaldiPL** [comment]
1. Turn off all other extensions.
2. Go to about: debugging
3. Click "Debug" below "Web pages scanner" and open the console
4. Perform all actions that do not work correctly. (adding pages etc.)
5. Make a screenshot of the console

**Comment by HFnp** [comment]
I have the same problem described in the first post.
I cannot, in any way, insert pages on web pages scanner. The popup notification say "the page is added", but is not ... the list is empty.

S.O. Windows 8.1 (64-bit) Firefox 71.0 (32-bit) web page scanner v1.9.4

**Comment by WaldiPL** [comment]
1. Go to about:debugging#/runtime/this-firefox

**Comment by WaldiPL** [comment]
- Go to about:debugging#/runtime/this-firefox
- Click "Debug" below "Web pages scanner" and open a console and clear it.
- Open the "Web pages scanner" in a sidebar

If there are any messages, copy and paste them into the comment.

Paste below code into the console and execute it.

```
var {changes,sites,sort,settings}=await browser.storage.local.get();
var out={settings};

var sortFolders=0;
var sortItems=0;
var sortErrorsArray=[];

if(!Array.isArray(sort)){
 sortErrorsArray.push(["Array","sort"]);
 console.error(["Array","sort"]);
}

sort.forEach((v,i)=>{
	if(!Array.isArray(v)){
		sortErrorsArray.push(["Array",i]);
		console.error(["Array",i]);
	}
	if(v.length!==5){
		sortErrorsArray.push(["length",i]);
	}
	if(typeof v[0]!=="string"||typeof v[1]!=="string"||typeof v[2]!=="string"||typeof v[3]!=="string"||typeof v[4]!=="boolean"){
		sortErrorsArray.push(["typeof",i]);
	}
	if((v[0].startsWith("folder")&&v[2]!=="folder")||(v[0].startsWith("item")&&v[2]!=="item")||(v[2]==="item"&&v[4]===true)){
		sortErrorsArray.push(["type",i]);
	}
	if(!v[0].length||!v[1].length||!v[2].length){
		sortErrorsArray.push(["empty",i]);
	}
	if(v[2]==="folder"){
		sortFolders++;
	}
	if(v[2]==="item"){
		sortItems++;
	}
});

var sortDebug={
	sortLength:sort.length,
	sortFolders,
	sortItems,
	sortErrorsArray
};

Object.assign(out,{sortDebug});

var sitesErrorsArray=[];

if(!Array.isArray(sites)){
	sitesErrorsArray.push(["Array","sites"]);
	console.error(["Array","sites"]);
}

sites.forEach((v,i)=>{
	if(typeof v!=="object"){
		sitesErrorsArray.push(["Object",i]);
		console.error(["Object",i]);
	}
	property(v,i,"broken","number");
	property(v,i,"changed","boolean");
	property(v,i,"charset","string");
	property(v,i,"date","number");
	property(v,i,"error","boolean");
	property(v,i,"favicon","string");
	property(v,i,"freq","number");
	property(v,i,"length","number");
	property(v,i,"md5","string");
	property(v,i,"mode","string");
	property(v,i,"newTime","object");
	property(v,i,"oldTime","object");
	property(v,i,"time","number");
	property(v,i,"title","string");
	property(v,i,"url","string");
});

function property(v,i,name,type){
	if(v.hasOwnProperty(name)){
		if(typeof v[name]!==type){
			sitesErrorsArray.push(["typeof",i,typeof v[name]]);
		}
	}else{
		if(name!=="error")sitesErrorsArray.push(["property",i,name]);
	}
}

var sitesDebug={
	sitesLength:sites.length,
	sitesErrorsArray
};

Object.assign(out,{sitesDebug});

var changesErrorsArray=[];

if(!Array.isArray(changes)){
	changesErrorsArray.push(["Array","changes"]);
	console.error(["Array","changes"]);
}

changes.forEach((v,i)=>{
	if(typeof v!=="object"){
		changesErrorsArray.push(["Object",i]);
		console.error(["Object",i]);
	}
	property2(v,i,"html","string");
	property2(v,i,"oldHtml","string");
});

function property2(v,i,name,type){
	if(v.hasOwnProperty(name)){
		if(typeof v[name]!==type){
			changesErrorsArray.push(["typeof",i,typeof v[name]]);
		}
	}else{
		changesErrorsArray.push(["property",i,name]);
	}
}

var changesDebug={
	changesLength:changes.length,
	changesErrorsArray
};

Object.assign(out,{changesDebug});

console.log(JSON.stringify(out));
```

If there are any messages, copy and paste them into the comment.

**Comment by HFnp** [comment]
1) when I opened "Web pages scanner" in a sidebar, the following error appear:
TypeError: sort is undefined           sidebar.js:243:3

Execute your code, returned the following messages:
TypeError: sites is undefined          shared.js:236:10
Array [ "Array", "sort" ]                    debugger eval code:28:13
TypeError: sort is undefined           debugger eval code:31:3

Forget to say, I'm using a portable version of Firefox 71, it makes any difference?

Thanks for your help!

**Comment by WaldiPL** [comment]
Did the extension work correctly before or did the problem occur immediately after installation?

Paste below code into the console and execute it.
```
browser.storage.local.get().then(e=>{
 console.log(JSON.stringify(e));
});
```
If there are any messages, copy and paste them into the comment.

**Comment by HFnp** [comment]
This is the message:

Promise { <state>: "pending" }

{"settings":{"notificationVolume":50,"notificationTime":13000,"showNotification":true,"autoOpen":false,"hideHeader":false,"defaultView":"light","openWindow":true,"openWindowMore":0,"requestTime":10000,"diffOld":false,"popupList":false,"theme":"light","showNextPrev":false,"scrollToFirstChange":false,"skipMinorChanges":false,"addToContextMenu":true,"changelog":false,"charset":"utf-8","period":5,"paused":false,"search":false,"delay":0,"highlightOutsideChanges":true,"scrollbarMarkers":false,"faviconService":"native"}}

**Comment by HFnp** [comment]
This is the same code executed with "Web Page Scanner" open in sidebar:

Promise { <state>: "pending" }

{"settings":{"notificationVolume":50,"notificationTime":13000,"showNotification":true,"autoOpen":false,"hideHeader":false,"defaultView":"light","openWindow":true,"openWindowMore":0,"requestTime":10000,"diffOld":false,"popupList":false,"theme":"light","showNextPrev":false,"scrollToFirstChange":false,"skipMinorChanges":false,"addToContextMenu":true,"changelog":false,"charset":"utf-8","period":5,"paused":false,"search":false,"delay":0,"highlightOutsideChanges":true,"scrollbarMarkers":false,"faviconService":"native"}}

**Comment by WaldiPL** [comment]
The database was not created after installation. In the next version I will make changes so that such situations do not occur.

To solve the problem paste the following code into the console and restart the browser.

`browser.storage.local.set({sites:[],changes:[],sort:[]});`

**Comment by HFnp** [comment]
Perfect, now it seems to work properly.

Thank you very much for your valuable help!

**Comment by dmarkdvt** [comment]
> The database was not created after installation. In the next version I will make changes so that such situations do not occur.
> 
> To solve the problem paste the following code into the console and restart the browser.
> 
> `browser.storage.local.set({sites:[],changes:[],sort:[]});`

Do I open the console with ctrl+shift+k like here?
https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console

I get this when I try to add the command.
```
browser.storage.local.set({sites:[],changes:[],sort:[]});
ReferenceError: browser is not defined
```

But this is my error msg when I try to add a page. I even tried to reinstall the plugin. Is it another bug?
```
ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. ExtensionStorageIDB.jsm:812
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:812
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:695
Error: An unexpected error occurred
```
