### ISSUE TITLE
Scanned items disappeared

### ISSUE THREAD

**Issue by rebuto** [WaldiPL/webpageScanner#40]
The command 
browser.storage.local.get('sites').then(result=>{
result into the following error :
TypeError: e.sites is undefined
Have I lost my webpages ?

**Comment by rebuto** [comment]
In about:debugging console, I get this : 

![image](https://user-images.githubusercontent.com/51235131/58985702-46afec00-87dc-11e9-8825-8dfba74e456d.png)

Are my pages lost ?

**Comment by WaldiPL** [comment]
- Open extension options
- Open the console and paste
`await browser.storage.local.get();`

What is the result?

**Comment by rebuto** [comment]
Thanks a lot for answering. 
Is this what you asked :
![image](https://user-images.githubusercontent.com/51235131/58987483-d905bf00-87df-11e9-9b5b-257576c71f88.png)

**Comment by WaldiPL** [comment]
Unfortunately, the database containing the pages has been removed.
To be able to add new pages, paste in the console
`browser.storage.local.set({sites:[],changes:[]);`

There is a small chance that a copy of the (outdated) data located in the browser profile.
- go to about:profiles and open main folder `C:\Users\\[Name]\AppData\Roaming\Mozilla\Firefox\Profiles\\[name]`
- open the folder `browser-extension-data\webpageScanner@waldemar.b`
- if the file "storage.js" exists, try to use it to restore the backup. (In the extension options)

**Comment by rebuto** [comment]
Thanks a lot.
I restored a backup from march.
