### ISSUE TITLE
CSS selector doesn't seem to work

### ISSUE THREAD

**Issue by tonyrulez** [WaldiPL/webpageScanner#41]
I want to monitor new listings on [this page](https://hardverapro.hu/aprok/hardver/keres.php?stext=&stmid=18157&buying=1&selling=1).

What I did is set to only scan a selection of the page, which is `#center`. As you can see on [this picture](https://i.vgy.me/EtUu8L.png) the highlighted area is `#center` (made with uBlock), however the scanner still scan the whole page. See [this picture](https://i.vgy.me/GXt5AE.png), as you can see the right side panel has the numbers highlighted, which are not part of `#center`, and I constantly get notifications because those number change all the time.

Then I tried `##li.media`. See [picture with uBlock](https://i.vgy.me/kAIddp.png), this section contains only the listings. Unfortunately I can't show you what updates the scanner showed, because it showed none... Scanner was running for a whole day with no updates while listings got posted on the watched site.

What am I missing? What else do I have to set to only watch the listings?

**Comment by WaldiPL** [comment]
Changes are detected only in the selected element. The page preview shows all changes, including those that are outside the selected element.
In the above example, the correct CSS selector is `#center`
In the last version (1.9.2), you can hide changes that are outside the selected element.
