### ISSUE TITLE
Possible UI improvement: Indicator counts down, when opening changed pages + Pause function

### ISSUE THREAD

**Issue by sphh** [WaldiPL/webpageScanner#42]
At the moment, the indicator showing the number of changed pages disappears, as soon as I press "Show changed pages", leaving me in the dark, how many pages are still there to be opened. I would find it very useful, if the indicator can count down.

Also useful would be an option, where I can pause the opening of changed pages and the possibility to resume later.

Thanks you for considering this.

**Comment by WaldiPL** [comment]
Proposed changes introduced in the new version.
