### ISSUE TITLE
No more button "afficher les pages modifiées"

### ISSUE THREAD

**Issue by rebuto** [WaldiPL/webpageScanner#43]
I hear the sound that means pages have been scanned but the button to access them has disappeared.

When I do scan now, pages I want to scan become blue in the list but when I click on them, I get a white page.

Could you help me please. This add-on is very useful for me.

**Comment by WaldiPL** [comment]
1. Create a backup copy of the database.
2. Open a scanned page.
3. Open console (ctrl + shift + k)
4. Copy visible messages and errors (or take a screenshot) and paste here.

**Comment by rebuto** [comment]
Thanks for your time WaldiPL
Unfortunately the backup button doesn't work :(

Here is the message :
![image](https://user-images.githubusercontent.com/51235131/73862269-a284b600-483e-11ea-91f1-34ddc44a07b1.png)

Here is the line in cause I presume :
![image](https://user-images.githubusercontent.com/51235131/73862439-dbbd2600-483e-11ea-8d68-658884f28496.png)

**Comment by WaldiPL** [comment]
Only this one message was in the console?
Open "Options", open the console and take a screenshot.

**Comment by rebuto** [comment]
After clicking here : 
![image](https://user-images.githubusercontent.com/51235131/73876337-1fbc2500-4857-11ea-8ea3-0c63659179ad.png)
This message appear :
![image](https://user-images.githubusercontent.com/51235131/73876407-3793a900-4857-11ea-867b-f93c9941446c.png)
When I click on "debugger eval code:1:53" come on this :
![image](https://user-images.githubusercontent.com/51235131/73876506-66118400-4857-11ea-9261-c6a2e40856b9.png)
does this mean the problem happens at th 41st character ? the e variable ?
I can't find the option button I've got a Firefox french version.

**Comment by WaldiPL** [comment]
I meant "extension options". Available by clicking the gear icon in the sidebar.
![](https://i.imgur.com/XqVXPR5.png)

Are you using version 1.9.5? The problem appeared after the update?
Have you used a debugger or console before the error occurred?

**Comment by WaldiPL** [comment]
I don't know if I understand your problem correctly.

> I hear the sound that means pages have been scanned but the button to access them has disappeared.

![](https://i.imgur.com/dAN3lWr.png)

If you mean this button, it is not visible if the pages are opened automatically ("Ouvrir automatiquement").

> When I do scan now, pages I want to scan become blue in the list but when I click on them, I get a white page.
When you open a page, only the scanner interface is visible? As below. Does changing the page view change anything?

![](https://i.imgur.com/49UkaVY.png)

>  Unfortunately the backup button doesn't work :(

1. Open options ("Gestion")
2. Open the console and clear it
3. Try to create a backup.
4. Take a console screenshot.

![](https://i.imgur.com/gwIAWdU.png)

**Comment by rebuto** [comment]
I've unchecked the box "Ouvri automatiquement and made another scan and got this :
![image](https://user-images.githubusercontent.com/51235131/73979739-01295d00-492f-11ea-9990-6f262bb223f7.png)

When I try to get a backup, I've got the same message in the console :
![image](https://user-images.githubusercontent.com/51235131/73979772-1d2cfe80-492f-11ea-884a-c873ac0100c4.png)

**Comment by WaldiPL** [comment]
Could you open the debugger and take a screenshot.

**Comment by rebuto** [comment]
yep 
![image](https://user-images.githubusercontent.com/51235131/73980139-e9060d80-492f-11ea-88c6-cf0f1fb463f9.png)

**Comment by WaldiPL** [comment]
1. Copy the script from the debugger and run it in the console. (is something new?)
2. Close the tab in the debugger.
3. Click the selected icon.

Check if something has changed.
Try disabling other extensions.

![](https://i.imgur.com/N1umOKo.png)

**Comment by rebuto** [comment]
1 :
![image](https://user-images.githubusercontent.com/51235131/73981797-57989a80-4933-11ea-8fac-4f6fb15431cb.png)

no differences
I disabled my other extensions and restarted firefox and tryed again. But still the same problem :(
Thanks again for your help

**Comment by WaldiPL** [comment]
What browser version are you using?

**Comment by rebuto** [comment]
72.0.2
![image](https://user-images.githubusercontent.com/51235131/73982796-42bd0680-4935-11ea-877f-11799135cd60.png)

**Comment by WaldiPL** [comment]
1. Open about:config
2. Search for "devtools.debugger"
3. Restore defaults for each option changed. (changed options are in bold)

![](https://i.imgur.com/yV3ncuQ.png)

**Comment by rebuto** [comment]
done.
I still get this error but I don't know how to get logs :
![image](https://user-images.githubusercontent.com/51235131/73984399-d6440680-4938-11ea-836a-0937f147a2b7.png)

Last message for me for today. It's time to go to bed ;)
I'll answer you as I wake up. Thanks again !

**Comment by WaldiPL** [comment]
Try to create a backup by pasting this script into the console.

```
  browser.storage.local.get().then(result => {
    let a = document.createElement("a");
    document.body.appendChild(a);
    let json = JSON.stringify(result),
      blob = new Blob([json], {
        type: "octet/stream"
      }),
      url = window.URL.createObjectURL(blob),
      d = new Date(),
      date = `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;
    a.href = url;
    a.download = `Web Pages Scanner - ${date}.json`;
    a.style.display = "none";
    a.click();
    window.URL.revokeObjectURL(url);
  });

```

**Comment by rebuto** [comment]
![image](https://user-images.githubusercontent.com/51235131/74064828-c6d5c380-49f3-11ea-9cc8-becc3d400e1c.png)

**Comment by WaldiPL** [comment]
Try to install the older version of the extension.
[Web Pages Scanner 1.9.4](https://addons.cdn.mozilla.net/user-media/addons/800531/skaner_stron-1.9.4-fx.xpi)

**Comment by rebuto** [comment]
![image](https://user-images.githubusercontent.com/51235131/74067512-b7f20f80-49f9-11ea-963c-9353897289c6.png)

After installing 1.9.4 I get the number on the icon :
![image](https://user-images.githubusercontent.com/51235131/74067551-d2c48400-49f9-11ea-98f9-1b439557ee47.png)
but I can't open modified pages and I still get error when I try to backup.

**Comment by WaldiPL** [comment]
Is the error displayed after the execution of the script `await browser.storage.local.get("changes");` is the same as before?

Can you delete a page, or add a new one?

**Comment by rebuto** [comment]
Yes, it's the same error.
When I add a page, I get this window
![image](https://user-images.githubusercontent.com/51235131/74081103-83a73f00-4a4b-11ea-8c2d-2d01e32d5a36.png)
But the page doesn't appear in the list.
I can't delete a page.

**Comment by WaldiPL** [comment]
Go to `about:devtools-toolbox?type=extension&id=webpageScanner%40waldemar.b`
Select the "Storage" tab and then "Extension Storage"
![](https://blog.nightly.mozilla.org/files/2019/08/webextensions-inspect-storage.png)
There should be four keys in the table: changes, settings, sites, sort. Is the key "changes" is visible?
Open the browser console (ctrl+shift+J) and take a screenshot.

Do you have any backups?

**Comment by rebuto** [comment]
There is nothing in the storage tab :+1: 
![image](https://user-images.githubusercontent.com/51235131/74098137-c97c0a00-4b14-11ea-8089-8da76a6adace.png)

**Comment by WaldiPL** [comment]
1. Open the "storage" tab (as above)
2. Open the browser console (ctrl+shift+J) and take a screenshot.

**Comment by rebuto** [comment]
hop :
![image](https://user-images.githubusercontent.com/51235131/74107592-075b4b80-4b72-11ea-9140-926a5d450fb8.png)

**Comment by WaldiPL** [comment]
Have you used other versions of Firefox?
Have you edited any files in a folder
`C:\Users\[user_name]\AppData\Roaming\Mozilla\Firefox\Profiles\[profile_name]\storage\default`

**Comment by rebuto** [comment]
Other versions yes. I upgrade as soon as there is a new version
I haven't edited any file in the default folder.

**Comment by WaldiPL** [comment]
I think one of a files containing a database is broken. These files are created by Firefox, and the extension does not impact this. Damaged is a part containing html code of scanned pages. Recovery of this data may be impossible. 

If you paste the code below into the console (on the "Web Pages Scanner" option page) you will create a backup containing the list of pages (everything that is visible in the sidebar (pages and their settings). 

```
	browser.storage.local.get(["sites","sort","settings"]).then(result=>{
		let a=document.createElement("a");
		document.body.appendChild(a);
		result.changes=[];
		for(let i=0;i<result.sites.length;i++){
			result.changes.push({"oldHtml":"","html":""});
		}
		let json=JSON.stringify(result),
			blob=new Blob([json],{type:"octet/stream"}),
			url=window.URL.createObjectURL(blob),
			d=new Date(),
			date=`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;
		a.href=url;
		a.download=`Web Pages Scanner - ${date}.json`;
		a.style.display="none";
		a.click();
		window.URL.revokeObjectURL(url);
	});
```

To remove the old database, you must uninstall and then reinstall the extension. Then you can restore the pages from the backup.

The backup created using the above script does not contain the content of the pages. So you need to scan all the pages again.

**Comment by rebuto** [comment]
I've reinstalled and restored the backup. It seems OK.
Thank you WaldiPL !
