### ISSUE TITLE
Web Pages Scanner not running

### ISSUE THREAD

**Issue by tomrich84** [WaldiPL/webpageScanner#44]
The extension appears to have broken and is no longer running updates when you hit 'scan now' I am using Firefox version 72.0.1 (64-bit)

**Comment by WaldiPL** [comment]
Try to install the older version of the extension.
[Web Pages Scanner 1.9.4](https://addons.cdn.mozilla.net/user-media/addons/800531/skaner_stron-1.9.4-fx.xpi)
