### ISSUE TITLE
Detect duplicates when adding a new page to watch

### ISSUE THREAD

**Issue by sphh** [WaldiPL/webpageScanner#47]
I know there is the option to delete duplicates from the management page. I would find it a huge improvement, if I were reminded when adding a page that I already added this page previously, maybe giving me the option to its setting page.

And a big thanks for your add-on!! It is one of those add-ons saving me a lot of time.

**Comment by WaldiPL** [comment]
In case you try to add a page that is already on the list, a notification will appear.
