### ISSUE TITLE
Show the scan list directly in the popup

### ISSUE THREAD

**Issue by Keith94** [WaldiPL/webpageScanner#5]
Is it possible to have the scan list entries displayed within the toolbar button popup itself, i.e. for quicker access?

**Comment by WaldiPL** [comment]
I added the ability to enable this feature in the settings.
Popup may have the wrong size.
If the popup closes too early, the data may not be saved.

**Comment by Keith94** [comment]
Awesome. Could you perhaps attach an XPI file so I can try out the latest version?

**Comment by Keith94** [comment]
Thanks! I'd like to make a suggestion: When clicking on the "Add new page" button, can you automatically fill in the address and title of the current page you're on? It saves some time to add pages while you're in the list view.

**Comment by WaldiPL** [comment]
I added an auto-fill button.
You can also add a page by context menu.

**Comment by Keith94** [comment]
OK, I tested the latest commit (you can remove the XPI if you want to ;)) and it works well.

I noticed right-clicking in the scan list (in popup) doesn't show the controls (edit, delete etc). Is that fixable?

**Comment by WaldiPL** [comment]
This bug is related to [1190679](https://bugzilla.mozilla.org/show_bug.cgi?id=1190679). Change "extensions.webextensions.remote" in about:config to make the context buttons work again.
