### ISSUE TITLE
Toolbar icon badge doesn't disappear upon clicking the only changed page in the popup menu in v1.9.6

### ISSUE THREAD

**Issue by FatOrangutan** [WaldiPL/webpageScanner#53]
0. Be on v1.19.6
1. Have one changed page
2. Click the blue row for the changed page in the toolbar popup menu

ER: The row for the changed page is no longer blue and the toolbar badge disappears

AR: While the row is indeed no longer blue, the toolbar badge remains.

**Comment by WaldiPL** [comment]
Thanks for reporting. Bug is fixed now.
