### ISSUE TITLE
Ignore all attributes of links

### ISSUE THREAD

**Issue by sphh** [WaldiPL/webpageScanner#54]
https://github.com/WaldiPL/webpageScanner/commit/12cddae9af310a8214b84ff30c636fb17d82a2d3 deals with the contents of the `href` attribute of `<a>` links (see #52). Now I came across the following link, where the attribute `data-cf-modified-...` changes the uuid every time the page is loaded:
```html
<a href="http://blog.mdpi.com/"
   onclick="if (!window.__cfRLUnblockHandlers) return false; ga('send', 'pageview', 'homeBlog');"
   target="_blank"
   rel="noopener noreferrer"
   data-cf-modified-cc0ad902b5c75365c865e8a0-="">
MDPI Blog
</a>
```
Would it be possible to also ignore **all** attributes - contents and attributes?

**Comment by WaldiPL** [comment]
In the new version added a possibility to ignore all attributes (also href) for all tags.
