### ISSUE TITLE
My Firefox 75.0 version of "Web pages scanner 2.0"  DOES NOT WORK

### ISSUE THREAD

**Issue by karinaardos** [WaldiPL/webpageScanner#58]
I really like this add-on. But after updating to version 2.0 Nothing works at all. It is not even possible to add a new page. The previous version works well.

**Comment by WaldiPL** [comment]
1. Create a backup in the settings
2. Disable other extensions
3. Restart your browser
4. Go to `about:debugging#/runtime/this-firefox`
5. Click **_Inspect_** next to Web Pages Scanner
6. Open a **_Console_**, make a screenshot
7. Try to open the sidebar or run the scanner
8. Open a **_Console_**, make a screenshot

**Comment by karinaardos** [comment]
I did everything as you said

https://i.onthe.io/smngozack980mvbn.b7f173e3.jpg
https://i.onthe.io/smngoz6jv0r3qhmnm.d8278e4c.jpg

**Comment by WaldiPL** [comment]
The problem only occurs in Firefox <78. The best option is to update your browser to the latest version. I will soon release a new version, in which the bug will be fixed.

**Comment by WaldiPL** [comment]
In the new version the bug has been fixed.
