### ISSUE TITLE
Opening the popup causes black bars to appear

### ISSUE THREAD

**Issue by Keith94** [WaldiPL/webpageScanner#6]
![2017-08-14_15-31-08](https://user-images.githubusercontent.com/5490615/29294751-ce1025e6-8105-11e7-9b76-3dec5044ac4b.gif)

**Comment by WaldiPL** [comment]
This bug is also related to [1390456](https://bugzilla.mozilla.org/show_bug.cgi?id=1390456)

**Comment by Keith94** [comment]
I see. `extensions.webextensions.remote;false` fixes that bug.
