### ISSUE TITLE
Issue in CSS Selector - "This page was not scanned."

### ISSUE THREAD

**Issue by derrikF** [WaldiPL/webpageScanner#60]
here is the address for scanning https://www.ph4.ru/b4_my.php?k=dictionary&q=mybible

here is a screenshot with the scan settings

![01](https://user-images.githubusercontent.com/4710022/110283873-d8700d00-7ff1-11eb-8414-64b7ddb3fc3f.png)

here is a screenshot of the area I choose to scan

![02](https://user-images.githubusercontent.com/4710022/110283961-0c4b3280-7ff2-11eb-8908-311f0c293dc3.png)

The error is this
> This page was not scanned. The problem occurred 7 times.

And such a problem when selecting any section on the page.

**Comment by WaldiPL** [comment]
Hi.
I will try to solve this problem in the future.
Below is an instruction to help you bypass this problem.

1. Add the web page to the scanner.
2. Open this web page (in the scanner) in a `New version` view .
3. Press Ctrl+Shift+C and pick an element.
4. Right-click on the selected element in the devtools panel, then click `Copy > Xpath`
5. Go to https://cssify.appspot.com and convert _xpath_ to _css selector_
6. Paste the copied selector into the scanner.

![](https://i.imgur.com/57m41M3.png)

**Comment by derrikF** [comment]
WOW! Great advice. Thanks!

**Comment by WaldiPL** [comment]
The problem has been fixed in version 2.1.0.
