### ISSUE TITLE
Delay before compare happens

### ISSUE THREAD

**Issue by oneilqut** [WaldiPL/webpageScanner#61]
Would it be feasible to add a field to set a delay (in seconds?) to wait before grabbing the fresh HTML and starting the comparison?

To give some in-page content loading time to complete.

Great add-on.

**Comment by WaldiPL** [comment]
Unfortunately, this is not possible.
No JS scripts are executed, so dynamic content loading causes problems and some pages may look wrong in the scanner.

**Comment by oneilqut** [comment]
Thanks, that makes sense.

And thanks for your quick reply.
