### ISSUE TITLE
Importing bookmarks from Bookmarks Toolbar

### ISSUE THREAD

**Issue by pm64** [WaldiPL/webpageScanner#63]
I attempted to import bookmarks from Bookmarks Toolbar, but received the error "Not found a folder called Bookmarks Toolbar. Check that the name is correct. The size of letters is important."

I seem to recall a limitation of the Firefox add-on API in which access was restricted to certain bookmark folders, though I just tried researching this and came up empty. Am I experiencing the effect of such a limitation?

**Comment by WaldiPL** [comment]
I think this is a Firefox bug. The root folder names are generated using `PlacesUtils.bookmarks.getLocalizedTitle`

Searching bookmarks by name only uses the titles used in the database `places.sqlite`
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/search

| Title | Database |
|------|------------|
| Bookmarks Toolbar | toolbar |
| Bookmarks Menu | menu |
| Other Bookmarks | unfiled |

Try using "toolbar", everything should work.

**Comment by pm64** [comment]
Thank you @WaldiPL, these names worked.

**Comment by WaldiPL** [comment]
The problem has been fixed in version 2.1.0.
