### ISSUE TITLE
Enhancement: Add folder support to bookmark import, allow deep import

### ISSUE THREAD

**Issue by pm64** [WaldiPL/webpageScanner#64]
I was excited to import all of my bookmarks in one swoop .. but then realized it would be impossible, since my bookmarks are organized into folders. This add-on supports folders in its database, so why not allow bookmark folders to be imported?

**Comment by WaldiPL** [comment]
In version 2.1.0, this has been improved. All sub-folders are flattened to one level.
The following bookmarks folder
```
[Imported folder]
- bookmark 1
- [sub-fodler 1]
- - bookmark a1
- - bookmark a2
- - [sub-folder 2]
- - - bookmark b1
- [sub-folder 3]
- - bookmark c1
```
on the scan list will look like this
```
bookmark 1
[sub-fodler 1]
- bookmark a1
- bookmark a2
- bookmark b1
[sub-folder 3]
- bookmark c1
```
