### ISSUE TITLE
Enhancement: Allow drag & drop of bookmarks

### ISSUE THREAD

**Issue by pm64** [WaldiPL/webpageScanner#65]
Allow bookmarks and/or bookmark folders to be dragged and dropped, either singularly or in a group, from places like the Library window, Bookmarks Toolbar, etc., into the Web Pages Scanner sidebar.

**Comment by WaldiPL** [comment]
In version 2.1.0, it is possible to drag: bookmarks, bookmark folders and links from any page to the sidebar for importing.
You can drag any page from the scan list, but it is not possible to drag an entire folder.
