### ISSUE TITLE
Cannot render a Tableau dashboard in the scanner

### ISSUE THREAD

**Issue by pcdavich** [WaldiPL/webpageScanner#66]
I want to monitor changes in a COVID-19 dashboard published in Tableau (https://tableau.itap.purdue.edu/t/public/views/PurdueFWCOVIDDashboard/PurdueFWDashboard?:isGuestRedirectFromVizportal=y&:embed=y). The scanner is unable to render the page in old or new version. I get notifications of changes, but no way of knowing which page element has been updated.
![webpagescanner2021-03-23_18-46-59](https://user-images.githubusercontent.com/81240721/112229238-f8feb080-8c08-11eb-847b-462ec9b3b3f9.png)

Any suggestions would be welcome.

**Comment by WaldiPL** [comment]
The content on this page is loaded via JS scripts. The scanner cannot run these scripts, therefore the page cannot be loaded.
