### ISSUE TITLE
"The selected element of partial scanning does not exist" even though it does

### ISSUE THREAD

**Issue by pm64** [WaldiPL/webpageScanner#69]
As a test, I configured Web Pages Scanner to scan the following page:
https://developers.google.com/android/images

The first time you visit this page, you're asked to accept an agreement. After clicking the button to accept the agreement, you're shown a list of factory images for different Android devices.

I used Web Pages Scanner's "Pick an element from the page" feature to select the TABLE element for the first table on the page, with the title "'redfin' for Pixel 5". Web Pages Scanner determined the following selector should be used: "#redfin   DIV > TABLE:nth-child(1)".

Some time later, Web Pages Scanner notified me that a change was detected. However, I am observing that the page actually has not changed at all. Furthermore, when using Web Pages Scanner to view the page, I see the error indicated in the title of this ticket: "The selected element of partial scanning does not exist".

Is this because Web Pages Scanner's web client doesn't share cookies with the main browser, causing the user agreement to remain unaccepted (and the table to not render) when the scan is later performed?

**Comment by WaldiPL** [comment]
The problem has been fixed in version 2.1.0. Try again to select the element to be scanned.
