### ISSUE TITLE
Add more scan intervals

### ISSUE THREAD

**Issue by sphh** [WaldiPL/webpageScanner#7]
It would be great to have more more scan intervals to select from. Once a week or in a fortnight is sometimes enough... Or make it even more configurable by using drop down menu with `minutes`, `hours`, `days` and an input box to give the number.

**Comment by WaldiPL** [comment]
This feature was added in version [1.3.2](https://github.com/WaldiPL/webpageScanner/blob/master/xpi/Web%20Pages%20Scanner%201.3.2.xpi?raw=true)
At the same time I was able to locate and remove the two major bugs related to the automatic scanning.
