### ISSUE TITLE
Delayed Load WebSite

### ISSUE THREAD

**Issue by ianalexis** [WaldiPL/webpageScanner#70]
Some sites wont have some delay to upload some data.
For example a track and trace page may need to load some data.
WPS checks the immediate site so cannot see any change on the data.
Maybe a 10s delay on the "saving current" stage may work.
If that's possible a custom time would be better.

**Comment by ianalexis** [comment]
For example: if i want to check a new bios release on https://www.gigabyte.com/ar/Motherboard/B450-AORUS-PRO-WIFI-rev-1x/support#support-dl-bios the page saved by WPS is almost empty.
![imagen](https://user-images.githubusercontent.com/12130714/125521885-cccec9d5-3f66-49d3-8873-258d17a7d9fd.png)

**Comment by WaldiPL** [comment]
Scripts are not executed in the scanner, so dynamic content loading does not work properly. The scanner only downloads the page code, similar to the "Show page source" view.
`view-source:https://www.gigabyte.com/ar/Motherboard/B450-AORUS-PRO-WIFI-rev-1x/support#support-dl-bios`
