### ISSUE TITLE
Scan list not working anymore

### ISSUE THREAD

**Issue by kirst-const** [WaldiPL/webpageScanner#75]
Clicking the toolbar icon only shows a small bar / border, but not the list of websites:
![image](https://user-images.githubusercontent.com/24697387/146784276-6eb2bc3d-abee-4b55-89b5-9b56089576a2.png)

The sidebar is also empty:
![image](https://user-images.githubusercontent.com/24697387/146786072-614f3134-a7e7-4cdb-8431-ae3a712cce91.png)

This started a few days ago.
I've tried disabling all other extensions and themes, but it didn't help.
Background scanning seems to work just fine.
Exporting all websites to bookmarks works just fine, too.

FF 95.0.2 64-bit

Any ideas?
Thank you very much for your work!

**Comment by WaldiPL** [comment]
Go to options and open 'scan list' in a new tab.
![img](https://i.imgur.com/PMBQsVU.png)
Then open a console (Ctrl+Shift+K) and copy all errors and warnings. Paste them here.

**Comment by kirst-const** [comment]
Thank you for your quick reply. I get 1 error:

```
Uncaught (in promise) TypeError: sites[id] is undefined             sidebar.js:241:9
    listSite moz-extension://c2eb5cf1-8881-4cfb-bd0f-4936f4fa3fbb/sidebar.js:241
    listSite moz-extension://c2eb5cf1-8881-4cfb-bd0f-4936f4fa3fbb/sidebar.js:233
    promise callback*listSite moz-extension://c2eb5cf1-8881-4cfb-bd0f-4936f4fa3fbb/sidebar.js:226
    <anonymous> moz-extension://c2eb5cf1-8881-4cfb-bd0f-4936f4fa3fbb/sidebar.js:22
    async* moz-extension://c2eb5cf1-8881-4cfb-bd0f-4936f4fa3fbb/sidebar.js:70
    listSite moz-extension://c2eb5cf1-8881-4cfb-bd0f-4936f4fa3fbb/sidebar.js:241
    forEach self-hosted:208
    listSite moz-extension://c2eb5cf1-8881-4cfb-bd0f-4936f4fa3fbb/sidebar.js:233
    (Async: promise callback)
    listSite moz-extension://c2eb5cf1-8881-4cfb-bd0f-4936f4fa3fbb/sidebar.js:226
    <anonymous> moz-extension://c2eb5cf1-8881-4cfb-bd0f-4936f4fa3fbb/sidebar.js:22
    AsyncFunctionNext self-hosted:695
    (Async: async)
    <anonymous> moz-extension://c2eb5cf1-8881-4cfb-bd0f-4936f4fa3fbb/sidebar.js:70
```

**Comment by kirst-const** [comment]
Creating a backup, un- and re-installing the extension and restoring the backup fixed the problem, btw. The extension now works again. Thank you for keeping up the good work!
