### ISSUE TITLE
Incompatibility with uMatrix add-on

### ISSUE THREAD

**Issue by wizard974** [WaldiPL/webpageScanner#8]
Hi,
I noticed that when [uMatrix](https://github.com/gorhill/uMatrix) from @gorhill is enable (active or not) it's impossible to add any page to scan list. (« Problem with adding page »).

Ubuntu 16.04
Firefox 55.0.2
webpageScanner 1.2.5
uMatrix 1.0.0

**Comment by gorhill** [comment]
Did you first try to diagnose by using uMatrix's logger to find out what is being blocked?

**Comment by wizard974** [comment]
My bad, I had forgotten to look at it. ^^'
After some tests, it seems that by adding the rule « matrix-off: moz-extension-scheme true » it works as expected.
Many thanks to you @gorhill
